# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_Application.ui'
#
# Created: Fri Feb 01 12:09:29 2019
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(870, 485)
        MainWindow.setMinimumSize(QtCore.QSize(870, 485))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        MainWindow.setWindowTitle(_fromUtf8(""))
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.LE_depenses = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LE_depenses.sizePolicy().hasHeightForWidth())
        self.LE_depenses.setSizePolicy(sizePolicy)
        self.LE_depenses.setMinimumSize(QtCore.QSize(100, 20))
        self.LE_depenses.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.LE_depenses.setFont(font)
        self.LE_depenses.setStyleSheet(_fromUtf8("background-color: rgb(240, 240, 240);"))
        self.LE_depenses.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LE_depenses.setReadOnly(True)
        self.LE_depenses.setObjectName(_fromUtf8("LE_depenses"))
        self.gridLayout.addWidget(self.LE_depenses, 1, 1, 1, 1)
        self.LE_reste = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LE_reste.sizePolicy().hasHeightForWidth())
        self.LE_reste.setSizePolicy(sizePolicy)
        self.LE_reste.setMinimumSize(QtCore.QSize(100, 20))
        self.LE_reste.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.LE_reste.setFont(font)
        self.LE_reste.setStyleSheet(_fromUtf8("background-color: rgb(240, 240, 240);"))
        self.LE_reste.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LE_reste.setReadOnly(True)
        self.LE_reste.setObjectName(_fromUtf8("LE_reste"))
        self.gridLayout.addWidget(self.LE_reste, 2, 1, 1, 1)
        self.LE_montant_paye = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LE_montant_paye.sizePolicy().hasHeightForWidth())
        self.LE_montant_paye.setSizePolicy(sizePolicy)
        self.LE_montant_paye.setMinimumSize(QtCore.QSize(100, 20))
        self.LE_montant_paye.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.LE_montant_paye.setFont(font)
        self.LE_montant_paye.setStyleSheet(_fromUtf8("background-color: rgb(240, 240, 240);"))
        self.LE_montant_paye.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LE_montant_paye.setReadOnly(True)
        self.LE_montant_paye.setObjectName(_fromUtf8("LE_montant_paye"))
        self.gridLayout.addWidget(self.LE_montant_paye, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(120, 20))
        self.label_2.setMaximumSize(QtCore.QSize(120, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(_fromUtf8("color: rgb(240, 240, 240);"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(120, 20))
        self.label.setMaximumSize(QtCore.QSize(120, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8("color: rgb(240, 240, 240);"))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(120, 20))
        self.label_3.setMaximumSize(QtCore.QSize(120, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(_fromUtf8("color: rgb(240, 240, 240);"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.TV_affichage = QtGui.QTableView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.TV_affichage.sizePolicy().hasHeightForWidth())
        self.TV_affichage.setSizePolicy(sizePolicy)
        self.TV_affichage.setMinimumSize(QtCore.QSize(770, 340))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.TV_affichage.setFont(font)
        self.TV_affichage.setStyleSheet(_fromUtf8("background-color: rgb(240, 240, 240);"))
        self.TV_affichage.setObjectName(_fromUtf8("TV_affichage"))
        self.verticalLayout_2.addWidget(self.TV_affichage)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.B_prelevements = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.B_prelevements.sizePolicy().hasHeightForWidth())
        self.B_prelevements.setSizePolicy(sizePolicy)
        self.B_prelevements.setMinimumSize(QtCore.QSize(100, 40))
        self.B_prelevements.setMaximumSize(QtCore.QSize(150, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.B_prelevements.setFont(font)
        self.B_prelevements.setObjectName(_fromUtf8("B_prelevements"))
        self.horizontalLayout.addWidget(self.B_prelevements)
        self.B_epargne = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.B_epargne.sizePolicy().hasHeightForWidth())
        self.B_epargne.setSizePolicy(sizePolicy)
        self.B_epargne.setMinimumSize(QtCore.QSize(100, 40))
        self.B_epargne.setMaximumSize(QtCore.QSize(150, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.B_epargne.setFont(font)
        self.B_epargne.setObjectName(_fromUtf8("B_epargne"))
        self.horizontalLayout.addWidget(self.B_epargne)
        self.B_depenses = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.B_depenses.sizePolicy().hasHeightForWidth())
        self.B_depenses.setSizePolicy(sizePolicy)
        self.B_depenses.setMinimumSize(QtCore.QSize(100, 40))
        self.B_depenses.setMaximumSize(QtCore.QSize(150, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.B_depenses.setFont(font)
        self.B_depenses.setObjectName(_fromUtf8("B_depenses"))
        self.horizontalLayout.addWidget(self.B_depenses)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.B_janvier = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.B_janvier.sizePolicy().hasHeightForWidth())
        self.B_janvier.setSizePolicy(sizePolicy)
        self.B_janvier.setMinimumSize(QtCore.QSize(75, 40))
        self.B_janvier.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.B_janvier.setFont(font)
        self.B_janvier.setObjectName(_fromUtf8("B_janvier"))
        self.verticalLayout.addWidget(self.B_janvier)
        self.B_fevrier = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.B_fevrier.sizePolicy().hasHeightForWidth())
        self.B_fevrier.setSizePolicy(sizePolicy)
        self.B_fevrier.setMinimumSize(QtCore.QSize(75, 40))
        self.B_fevrier.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.B_fevrier.setFont(font)
        self.B_fevrier.setObjectName(_fromUtf8("B_fevrier"))
        self.verticalLayout.addWidget(self.B_fevrier)
        self.B_mars = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.B_mars.sizePolicy().hasHeightForWidth())
        self.B_mars.setSizePolicy(sizePolicy)
        self.B_mars.setMinimumSize(QtCore.QSize(75, 40))
        self.B_mars.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.B_mars.setFont(font)
        self.B_mars.setObjectName(_fromUtf8("B_mars"))
        self.verticalLayout.addWidget(self.B_mars)
        self.B_avril = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.B_avril.sizePolicy().hasHeightForWidth())
        self.B_avril.setSizePolicy(sizePolicy)
        self.B_avril.setMinimumSize(QtCore.QSize(75, 40))
        self.B_avril.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.B_avril.setFont(font)
        self.B_avril.setObjectName(_fromUtf8("B_avril"))
        self.verticalLayout.addWidget(self.B_avril)
        self.B_mai = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.B_mai.sizePolicy().hasHeightForWidth())
        self.B_mai.setSizePolicy(sizePolicy)
        self.B_mai.setMinimumSize(QtCore.QSize(75, 40))
        self.B_mai.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.B_mai.setFont(font)
        self.B_mai.setObjectName(_fromUtf8("B_mai"))
        self.verticalLayout.addWidget(self.B_mai)
        self.B_juin = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.B_juin.sizePolicy().hasHeightForWidth())
        self.B_juin.setSizePolicy(sizePolicy)
        self.B_juin.setMinimumSize(QtCore.QSize(75, 40))
        self.B_juin.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.B_juin.setFont(font)
        self.B_juin.setObjectName(_fromUtf8("B_juin"))
        self.verticalLayout.addWidget(self.B_juin)
        self.B_juillet = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.B_juillet.sizePolicy().hasHeightForWidth())
        self.B_juillet.setSizePolicy(sizePolicy)
        self.B_juillet.setMinimumSize(QtCore.QSize(75, 40))
        self.B_juillet.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.B_juillet.setFont(font)
        self.B_juillet.setObjectName(_fromUtf8("B_juillet"))
        self.verticalLayout.addWidget(self.B_juillet)
        self.B_aout = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.B_aout.sizePolicy().hasHeightForWidth())
        self.B_aout.setSizePolicy(sizePolicy)
        self.B_aout.setMinimumSize(QtCore.QSize(75, 40))
        self.B_aout.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.B_aout.setFont(font)
        self.B_aout.setObjectName(_fromUtf8("B_aout"))
        self.verticalLayout.addWidget(self.B_aout)
        self.B_septembre = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.B_septembre.sizePolicy().hasHeightForWidth())
        self.B_septembre.setSizePolicy(sizePolicy)
        self.B_septembre.setMinimumSize(QtCore.QSize(75, 40))
        self.B_septembre.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.B_septembre.setFont(font)
        self.B_septembre.setObjectName(_fromUtf8("B_septembre"))
        self.verticalLayout.addWidget(self.B_septembre)
        self.B_octobre = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.B_octobre.sizePolicy().hasHeightForWidth())
        self.B_octobre.setSizePolicy(sizePolicy)
        self.B_octobre.setMinimumSize(QtCore.QSize(75, 40))
        self.B_octobre.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.B_octobre.setFont(font)
        self.B_octobre.setObjectName(_fromUtf8("B_octobre"))
        self.verticalLayout.addWidget(self.B_octobre)
        self.B_novembre = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.B_novembre.sizePolicy().hasHeightForWidth())
        self.B_novembre.setSizePolicy(sizePolicy)
        self.B_novembre.setMinimumSize(QtCore.QSize(75, 40))
        self.B_novembre.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.B_novembre.setFont(font)
        self.B_novembre.setObjectName(_fromUtf8("B_novembre"))
        self.verticalLayout.addWidget(self.B_novembre)
        self.B_decembre = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.B_decembre.sizePolicy().hasHeightForWidth())
        self.B_decembre.setSizePolicy(sizePolicy)
        self.B_decembre.setMinimumSize(QtCore.QSize(75, 40))
        self.B_decembre.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.B_decembre.setFont(font)
        self.B_decembre.setObjectName(_fromUtf8("B_decembre"))
        self.verticalLayout.addWidget(self.B_decembre)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.LE_montant_paye, self.LE_depenses)
        MainWindow.setTabOrder(self.LE_depenses, self.LE_reste)
        MainWindow.setTabOrder(self.LE_reste, self.B_avril)
        MainWindow.setTabOrder(self.B_avril, self.B_mai)
        MainWindow.setTabOrder(self.B_mai, self.B_juin)
        MainWindow.setTabOrder(self.B_juin, self.B_juillet)
        MainWindow.setTabOrder(self.B_juillet, self.B_aout)
        MainWindow.setTabOrder(self.B_aout, self.B_septembre)
        MainWindow.setTabOrder(self.B_septembre, self.B_octobre)
        MainWindow.setTabOrder(self.B_octobre, self.B_novembre)
        MainWindow.setTabOrder(self.B_novembre, self.B_decembre)
        MainWindow.setTabOrder(self.B_decembre, self.B_prelevements)
        MainWindow.setTabOrder(self.B_prelevements, self.B_epargne)
        MainWindow.setTabOrder(self.B_epargne, self.B_depenses)
        MainWindow.setTabOrder(self.B_depenses, self.B_mars)
        MainWindow.setTabOrder(self.B_mars, self.B_fevrier)
        MainWindow.setTabOrder(self.B_fevrier, self.B_janvier)
        MainWindow.setTabOrder(self.B_janvier, self.TV_affichage)

    def retranslateUi(self, MainWindow):
        self.label_2.setText(_translate("MainWindow", "Dépenses", None))
        self.label.setText(_translate("MainWindow", "Montant paye", None))
        self.label_3.setText(_translate("MainWindow", "Reste", None))
        self.B_prelevements.setText(_translate("MainWindow", "Prélèvements", None))
        self.B_epargne.setText(_translate("MainWindow", "Epargne", None))
        self.B_depenses.setText(_translate("MainWindow", "Dépenses", None))
        self.B_janvier.setText(_translate("MainWindow", "Janvier", None))
        self.B_fevrier.setText(_translate("MainWindow", "Février", None))
        self.B_mars.setText(_translate("MainWindow", "Mars", None))
        self.B_avril.setText(_translate("MainWindow", "Avril", None))
        self.B_mai.setText(_translate("MainWindow", "Mai", None))
        self.B_juin.setText(_translate("MainWindow", "Juin", None))
        self.B_juillet.setText(_translate("MainWindow", "Juillet", None))
        self.B_aout.setText(_translate("MainWindow", "Août", None))
        self.B_septembre.setText(_translate("MainWindow", "Septembre", None))
        self.B_octobre.setText(_translate("MainWindow", "Octobre", None))
        self.B_novembre.setText(_translate("MainWindow", "Novembre", None))
        self.B_decembre.setText(_translate("MainWindow", "Décembre", None))

