# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_Dupliquer_donnees_mois.ui'
#
# Created: Tue Feb 12 14:14:07 2019
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(440, 270)
        Dialog.setMinimumSize(QtCore.QSize(440, 270))
        Dialog.setMaximumSize(QtCore.QSize(440, 270))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Dialog.setPalette(palette)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.l_libelle = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_libelle.sizePolicy().hasHeightForWidth())
        self.l_libelle.setSizePolicy(sizePolicy)
        self.l_libelle.setMinimumSize(QtCore.QSize(250, 20))
        self.l_libelle.setMaximumSize(QtCore.QSize(250, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.l_libelle.setFont(font)
        self.l_libelle.setStyleSheet(_fromUtf8("color: rgb(240, 240, 240);"))
        self.l_libelle.setObjectName(_fromUtf8("l_libelle"))
        self.gridLayout.addWidget(self.l_libelle, 0, 0, 1, 1)
        self.CB_categorie = QtGui.QComboBox(Dialog)
        self.CB_categorie.setMinimumSize(QtCore.QSize(140, 30))
        self.CB_categorie.setMaximumSize(QtCore.QSize(140, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.CB_categorie.setFont(font)
        self.CB_categorie.setObjectName(_fromUtf8("CB_categorie"))
        self.CB_categorie.addItem(_fromUtf8(""))
        self.CB_categorie.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.CB_categorie, 0, 1, 1, 1)
        self.l_montant = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_montant.sizePolicy().hasHeightForWidth())
        self.l_montant.setSizePolicy(sizePolicy)
        self.l_montant.setMinimumSize(QtCore.QSize(250, 50))
        self.l_montant.setMaximumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.l_montant.setFont(font)
        self.l_montant.setStyleSheet(_fromUtf8("color: rgb(240, 240, 240);"))
        self.l_montant.setObjectName(_fromUtf8("l_montant"))
        self.gridLayout.addWidget(self.l_montant, 1, 0, 1, 1)
        self.CB_mois_source = QtGui.QComboBox(Dialog)
        self.CB_mois_source.setMinimumSize(QtCore.QSize(140, 40))
        self.CB_mois_source.setMaximumSize(QtCore.QSize(140, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.CB_mois_source.setFont(font)
        self.CB_mois_source.setObjectName(_fromUtf8("CB_mois_source"))
        self.gridLayout.addWidget(self.CB_mois_source, 1, 1, 1, 1)
        self.l_montant_2 = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_montant_2.sizePolicy().hasHeightForWidth())
        self.l_montant_2.setSizePolicy(sizePolicy)
        self.l_montant_2.setMinimumSize(QtCore.QSize(250, 50))
        self.l_montant_2.setMaximumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.l_montant_2.setFont(font)
        self.l_montant_2.setStyleSheet(_fromUtf8("color: rgb(240, 240, 240);"))
        self.l_montant_2.setObjectName(_fromUtf8("l_montant_2"))
        self.gridLayout.addWidget(self.l_montant_2, 2, 0, 1, 1)
        self.CB_mois_destination = QtGui.QComboBox(Dialog)
        self.CB_mois_destination.setMinimumSize(QtCore.QSize(140, 40))
        self.CB_mois_destination.setMaximumSize(QtCore.QSize(140, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.CB_mois_destination.setFont(font)
        self.CB_mois_destination.setObjectName(_fromUtf8("CB_mois_destination"))
        self.CB_mois_destination.addItem(_fromUtf8(""))
        self.CB_mois_destination.addItem(_fromUtf8(""))
        self.CB_mois_destination.addItem(_fromUtf8(""))
        self.CB_mois_destination.addItem(_fromUtf8(""))
        self.CB_mois_destination.addItem(_fromUtf8(""))
        self.CB_mois_destination.addItem(_fromUtf8(""))
        self.CB_mois_destination.addItem(_fromUtf8(""))
        self.CB_mois_destination.addItem(_fromUtf8(""))
        self.CB_mois_destination.addItem(_fromUtf8(""))
        self.CB_mois_destination.addItem(_fromUtf8(""))
        self.CB_mois_destination.addItem(_fromUtf8(""))
        self.CB_mois_destination.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.CB_mois_destination, 2, 1, 1, 1)
        self.l_vide = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_vide.sizePolicy().hasHeightForWidth())
        self.l_vide.setSizePolicy(sizePolicy)
        self.l_vide.setMinimumSize(QtCore.QSize(400, 20))
        self.l_vide.setMaximumSize(QtCore.QSize(400, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.l_vide.setFont(font)
        self.l_vide.setStyleSheet(_fromUtf8("color: rgb(240, 240, 240);"))
        self.l_vide.setText(_fromUtf8(""))
        self.l_vide.setObjectName(_fromUtf8("l_vide"))
        self.gridLayout.addWidget(self.l_vide, 3, 0, 1, 2)
        self.B_dupliquer = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.B_dupliquer.sizePolicy().hasHeightForWidth())
        self.B_dupliquer.setSizePolicy(sizePolicy)
        self.B_dupliquer.setMinimumSize(QtCore.QSize(140, 40))
        self.B_dupliquer.setMaximumSize(QtCore.QSize(140, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.B_dupliquer.setFont(font)
        self.B_dupliquer.setObjectName(_fromUtf8("B_dupliquer"))
        self.gridLayout.addWidget(self.B_dupliquer, 4, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dupliquer un mois", None))
        self.l_libelle.setText(_translate("Dialog", "Catégorie", None))
        self.CB_categorie.setItemText(0, _translate("Dialog", "Prélèvements", None))
        self.CB_categorie.setItemText(1, _translate("Dialog", "Epargnes", None))
        self.l_montant.setText(_translate("Dialog", "<html><head/><body><p>Sélectionnez le mois qui</p><p>contient les données à dupliquer</p></body></html>", None))
        self.l_montant_2.setText(_translate("Dialog", "<html><head/><body><p>Sélectionnez le mois qui va</p><p>contenir les données dupliquées</p></body></html>", None))
        self.CB_mois_destination.setItemText(0, _translate("Dialog", "Janvier", None))
        self.CB_mois_destination.setItemText(1, _translate("Dialog", "Février", None))
        self.CB_mois_destination.setItemText(2, _translate("Dialog", "Mars", None))
        self.CB_mois_destination.setItemText(3, _translate("Dialog", "Avril", None))
        self.CB_mois_destination.setItemText(4, _translate("Dialog", "Mai", None))
        self.CB_mois_destination.setItemText(5, _translate("Dialog", "Juin", None))
        self.CB_mois_destination.setItemText(6, _translate("Dialog", "Juillet", None))
        self.CB_mois_destination.setItemText(7, _translate("Dialog", "Août", None))
        self.CB_mois_destination.setItemText(8, _translate("Dialog", "Septembre", None))
        self.CB_mois_destination.setItemText(9, _translate("Dialog", "Octobre", None))
        self.CB_mois_destination.setItemText(10, _translate("Dialog", "Novembre", None))
        self.CB_mois_destination.setItemText(11, _translate("Dialog", "Décembre", None))
        self.B_dupliquer.setText(_translate("Dialog", "Dupliquer", None))

